CREATE TABLE `automation_events` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`automation_id` integer NOT NULL,
	`connection_id` integer NOT NULL,
	`instagram_comment_id` text NOT NULL,
	`instagram_media_id` text,
	`instagram_user_id` text,
	`username` text DEFAULT 'instagram_user' NOT NULL,
	`comment_text` text DEFAULT '' NOT NULL,
	`matched_keyword` text,
	`public_reply` text,
	`dm_message` text,
	`asset_id` integer,
	`destination_url` text,
	`tracking_token` text NOT NULL,
	`meta_reply_id` text,
	`meta_message_id` text,
	`status` text DEFAULT 'Recebido' NOT NULL,
	`error` text,
	`clicked_at` text,
	`processed_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `automation_events_instagram_comment_id_unique` ON `automation_events` (`instagram_comment_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `automation_events_tracking_token_unique` ON `automation_events` (`tracking_token`);--> statement-breakpoint
CREATE TABLE `automation_funnels` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`owner_email` text NOT NULL,
	`account_id` integer NOT NULL,
	`name` text NOT NULL,
	`template_type` text DEFAULT 'lead_magnet' NOT NULL,
	`status` text DEFAULT 'Rascunho' NOT NULL,
	`trigger_type` text DEFAULT 'keywords' NOT NULL,
	`media_id` text,
	`media_label` text,
	`match_type` text DEFAULT 'contains' NOT NULL,
	`keywords` text DEFAULT '[]' NOT NULL,
	`public_reply_enabled` integer DEFAULT true NOT NULL,
	`reply_mode` text DEFAULT 'random' NOT NULL,
	`reply_scripts` text DEFAULT '[]' NOT NULL,
	`dm_message` text DEFAULT '' NOT NULL,
	`dm_button_label` text DEFAULT 'Acessar material' NOT NULL,
	`dm_link` text,
	`asset_id` integer,
	`cooldown_hours` integer DEFAULT 24 NOT NULL,
	`ignore_own_comments` integer DEFAULT true NOT NULL,
	`blocked_words` text DEFAULT '[]' NOT NULL,
	`blocked_users` text DEFAULT '[]' NOT NULL,
	`comments_count` integer DEFAULT 0 NOT NULL,
	`replies_sent` integer DEFAULT 0 NOT NULL,
	`dms_sent` integer DEFAULT 0 NOT NULL,
	`clicks` integer DEFAULT 0 NOT NULL,
	`leads` integer DEFAULT 0 NOT NULL,
	`last_run_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
