import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const brandAccounts = sqliteTable("brand_accounts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ownerEmail: text("owner_email").notNull().default(""),
  name: text("name").notNull(),
  handle: text("handle").notNull(),
  platform: text("platform").notNull().default("Instagram"),
  initials: text("initials").notNull().default("IG"),
  accent: text("accent").notNull().default("#B8FF6A"),
  connectionStatus: text("connection_status").notNull().default("Planejamento"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const contentItems = sqliteTable("content_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  accountId: integer("account_id").notNull().default(1),
  title: text("title").notNull(),
  kind: text("kind").notNull().default("Ideia"),
  status: text("status").notNull().default("Ideia"),
  platform: text("platform").notNull().default("Instagram"),
  pillar: text("pillar").notNull().default("Criatividade"),
  hook: text("hook").notNull().default(""),
  body: text("body").notNull().default(""),
  scheduledAt: text("scheduled_at"),
  publishedAt: text("published_at"),
  reach: integer("reach").notNull().default(0),
  saves: integer("saves").notNull().default(0),
  comments: integer("comments").notNull().default(0),
  parentSourceId: integer("parent_source_id"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const sourceBases = sqliteTable("source_bases", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  accountId: integer("account_id").notNull().default(1),
  title: text("title").notNull(),
  sourceText: text("source_text").notNull(),
  thesis: text("thesis").notNull().default(""),
  angles: text("angles").notNull().default("[]"),
  proofs: text("proofs").notNull().default("[]"),
  objections: text("objections").notNull().default("[]"),
  cta: text("cta").notNull().default(""),
  status: text("status").notNull().default("Rascunho"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const libraryAssets = sqliteTable("library_assets", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  accountId: integer("account_id").notNull().default(1),
  title: text("title").notNull(),
  category: text("category").notNull(),
  format: text("format").notNull().default("Documento"),
  status: text("status").notNull().default("Rascunho"),
  description: text("description").notNull().default(""),
  url: text("url"),
  storageKey: text("storage_key"),
  fileName: text("file_name"),
  mimeType: text("mime_type"),
  fileSize: integer("file_size").notNull().default(0),
  conversions: integer("conversions").notNull().default(0),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const instagramOauthStates = sqliteTable("instagram_oauth_states", {
  state: text("state").primaryKey(),
  ownerEmail: text("owner_email").notNull(),
  accountId: integer("account_id").notNull(),
  expiresAt: text("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const instagramConnections = sqliteTable("instagram_connections", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ownerEmail: text("owner_email").notNull(),
  accountId: integer("account_id").notNull().unique(),
  instagramUserId: text("instagram_user_id").notNull(),
  username: text("username").notNull(),
  accountType: text("account_type").notNull().default("PROFESSIONAL"),
  profilePictureUrl: text("profile_picture_url"),
  tokenCiphertext: text("token_ciphertext").notNull(),
  tokenIv: text("token_iv").notNull(),
  tokenExpiresAt: text("token_expires_at").notNull(),
  status: text("status").notNull().default("Conectado"),
  followersCount: integer("followers_count").notNull().default(0),
  mediaCount: integer("media_count").notNull().default(0),
  reach30d: integer("reach_30d").notNull().default(0),
  views30d: integer("views_30d").notNull().default(0),
  profileViews30d: integer("profile_views_30d").notNull().default(0),
  interactions30d: integer("interactions_30d").notNull().default(0),
  lastSyncedAt: text("last_synced_at"),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const instagramMedia = sqliteTable("instagram_media", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  connectionId: integer("connection_id").notNull(),
  instagramMediaId: text("instagram_media_id").notNull().unique(),
  caption: text("caption").notNull().default(""),
  mediaType: text("media_type").notNull().default("IMAGE"),
  permalink: text("permalink").notNull().default(""),
  publishedAt: text("published_at").notNull(),
  reach: integer("reach").notNull().default(0),
  views: integer("views").notNull().default(0),
  likes: integer("likes").notNull().default(0),
  comments: integer("comments").notNull().default(0),
  saves: integer("saves").notNull().default(0),
  shares: integer("shares").notNull().default(0),
  totalInteractions: integer("total_interactions").notNull().default(0),
  syncedAt: text("synced_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const automationFunnels = sqliteTable("automation_funnels", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ownerEmail: text("owner_email").notNull(),
  accountId: integer("account_id").notNull(),
  name: text("name").notNull(),
  templateType: text("template_type").notNull().default("lead_magnet"),
  status: text("status").notNull().default("Rascunho"),
  triggerType: text("trigger_type").notNull().default("keywords"),
  mediaId: text("media_id"),
  mediaLabel: text("media_label"),
  matchType: text("match_type").notNull().default("contains"),
  keywords: text("keywords").notNull().default("[]"),
  publicReplyEnabled: integer("public_reply_enabled", { mode: "boolean" }).notNull().default(true),
  replyMode: text("reply_mode").notNull().default("random"),
  replyScripts: text("reply_scripts").notNull().default("[]"),
  dmMessage: text("dm_message").notNull().default(""),
  dmButtonLabel: text("dm_button_label").notNull().default("Acessar material"),
  dmLink: text("dm_link"),
  assetId: integer("asset_id"),
  cooldownHours: integer("cooldown_hours").notNull().default(24),
  ignoreOwnComments: integer("ignore_own_comments", { mode: "boolean" }).notNull().default(true),
  blockedWords: text("blocked_words").notNull().default("[]"),
  blockedUsers: text("blocked_users").notNull().default("[]"),
  commentsCount: integer("comments_count").notNull().default(0),
  repliesSent: integer("replies_sent").notNull().default(0),
  dmsSent: integer("dms_sent").notNull().default(0),
  clicks: integer("clicks").notNull().default(0),
  leads: integer("leads").notNull().default(0),
  lastRunAt: text("last_run_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const automationEvents = sqliteTable("automation_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  automationId: integer("automation_id").notNull(),
  connectionId: integer("connection_id").notNull(),
  instagramCommentId: text("instagram_comment_id").notNull().unique(),
  instagramMediaId: text("instagram_media_id"),
  instagramUserId: text("instagram_user_id"),
  username: text("username").notNull().default("instagram_user"),
  commentText: text("comment_text").notNull().default(""),
  matchedKeyword: text("matched_keyword"),
  publicReply: text("public_reply"),
  dmMessage: text("dm_message"),
  assetId: integer("asset_id"),
  destinationUrl: text("destination_url"),
  trackingToken: text("tracking_token").notNull().unique(),
  metaReplyId: text("meta_reply_id"),
  metaMessageId: text("meta_message_id"),
  status: text("status").notNull().default("Recebido"),
  error: text("error"),
  clickedAt: text("clicked_at"),
  processedAt: text("processed_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
